# Generated by Django 3.0.6 on 2020-05-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virus_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epidemiology',
            name='name',
        ),
    ]
