# Generated by Django 3.0.6 on 2020-05-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_app', '0002_remove_epidemiology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus',
            name='photo',
            field=models.ImageField(default='static/img/viruses/base_virus.jpg', upload_to='virus_app/static/img/viruses'),
        ),
    ]
