# Generated by Django 3.0.6 on 2020-05-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_app', '0003_auto_20200512_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus',
            name='photo',
            field=models.ImageField(default='img/viruses/base_virus.jpg', upload_to='img/viruses'),
        ),
    ]
