# Generated by Django 3.0.6 on 2020-05-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_app', '0004_auto_20200512_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='town',
            field=models.CharField(max_length=100),
        ),
    ]
