# Generated by Django 3.0.6 on 2020-05-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virus_app', '0005_auto_20200512_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedemography',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virus_app.Period'),
        ),
        migrations.AlterField(
            model_name='placedemography',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virus_app.Place'),
        ),
    ]
