# Generated by Django 3.0.6 on 2020-05-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_app', '0007_auto_20200512_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemiology',
            name='structure',
            field=models.CharField(choices=[('С', 'Спиральный'), ('И', 'Икосаэдрический'), ('П', 'Продолговатый'), ('Км', 'Комплексный')], max_length=2),
        ),
    ]
