# Generated by Django 3.0.6 on 2020-09-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_app', '0012_auto_20200904_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemic',
            name='more_info',
            field=models.TextField(default='Краткие сведения об эпидемии конкретного вируса.'),
        ),
        migrations.AddField(
            model_name='epidemic',
            name='photo',
            field=models.ImageField(default='img/epidemic_countries/base_country.jpg', upload_to='img/epidemic_countries'),
        ),
    ]
