# Generated by Django 3.0.6 on 2020-09-14 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virus_app', '0013_auto_20200910_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='more_info',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='place_demography',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='epidemic',
        ),
        migrations.AddField(
            model_name='favourites',
            name='epidemic',
            field=models.ManyToManyField(blank=True, to='virus_app.Epidemic'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='virus',
        ),
        migrations.AddField(
            model_name='favourites',
            name='virus',
            field=models.ManyToManyField(blank=True, to='virus_app.Virus'),
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('СА', 'Северная Америка'), ('ЮА', 'Южная Америка'), ('Аф', 'Африка'), ('Е', 'Европа'), ('Аз', 'Азия'), ('Ав', 'Австралия'), ('Ан', 'Антарктида')], max_length=2)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('town', models.CharField(max_length=100)),
                ('epidemic', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='virus_app.Epidemic')),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virus_app.Favourites')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('СА', 'Северная Америка'), ('ЮА', 'Южная Америка'), ('Аф', 'Африка'), ('Е', 'Европа'), ('Аз', 'Азия'), ('Ав', 'Австралия'), ('Ан', 'Антарктида')], max_length=2)),
                ('epidemic', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='virus_app.Epidemic')),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virus_app.Favourites')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('СА', 'Северная Америка'), ('ЮА', 'Южная Америка'), ('Аф', 'Африка'), ('Е', 'Европа'), ('Аз', 'Азия'), ('Ав', 'Австралия'), ('Ан', 'Антарктида')], max_length=2)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('epidemic', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='virus_app.Epidemic')),
                ('favourite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virus_app.Favourites')),
            ],
        ),
    ]
