# Generated by Django 3.0.6 on 2020-09-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virus_app', '0014_auto_20200914_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='virus_app.Favourites'),
        ),
    ]
