# Generated by Django 3.0.6 on 2020-09-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus_app', '0016_auto_20200914_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='epidemic',
        ),
        migrations.RemoveField(
            model_name='region',
            name='epidemic',
        ),
        migrations.RemoveField(
            model_name='town',
            name='epidemic',
        ),
        migrations.AddField(
            model_name='country',
            name='epidemic_id',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='region',
            name='epidemic_id',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='town',
            name='epidemic_id',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
